# Site settings
title: Tenkaklet's Blog
email: maximus@tenkaklet.com
description: > # this means to ignore newlines until "baseurl:"
  Max is a Web Designer, Documentarian and almost a distinguished Musician.
  He has worked with many different media projects on and off since 2010. 
  He is  the creator of Tenkaklet Productions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tenkaklet
github_username:  tenkaklet

# Build settings
markdown: kramdown

permalink: /:title/
